// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB45uvtdo7X99fLkfEMnd8vm5j-22yR__s',
    appId: '1:322428012079:web:c3f10e612481026627a8da',
    messagingSenderId: '322428012079',
    projectId: 'atlas-55566',
    authDomain: 'atlas-55566.firebaseapp.com',
    storageBucket: 'atlas-55566.firebasestorage.app',
    measurementId: 'G-ZM7Y1LDQDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxsvxCa3VmTN3_TAxl1dOy-91he8H19S4',
    appId: '1:322428012079:android:263c26bd8f73774d27a8da',
    messagingSenderId: '322428012079',
    projectId: 'atlas-55566',
    storageBucket: 'atlas-55566.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH5_VTatBSOxX8kdnEq_0XwKTxtd3NyLQ',
    appId: '1:322428012079:ios:da63ffa53106862c27a8da',
    messagingSenderId: '322428012079',
    projectId: 'atlas-55566',
    storageBucket: 'atlas-55566.firebasestorage.app',
    iosBundleId: 'com.example.trabalhoMarcioMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH5_VTatBSOxX8kdnEq_0XwKTxtd3NyLQ',
    appId: '1:322428012079:ios:da63ffa53106862c27a8da',
    messagingSenderId: '322428012079',
    projectId: 'atlas-55566',
    storageBucket: 'atlas-55566.firebasestorage.app',
    iosBundleId: 'com.example.trabalhoMarcioMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB45uvtdo7X99fLkfEMnd8vm5j-22yR__s',
    appId: '1:322428012079:web:59fb054a8dcf713027a8da',
    messagingSenderId: '322428012079',
    projectId: 'atlas-55566',
    authDomain: 'atlas-55566.firebaseapp.com',
    storageBucket: 'atlas-55566.firebasestorage.app',
    measurementId: 'G-PDVS4Y005H',
  );
}
